module.exports = {
  preset: "ts-jest",
  roots: ["<rootDir>/src"],
  testEnvironment: "jsdom",
  setupFilesAfterEnv: ["<rootDir>/src/test/setupTests.ts"],
  clearMocks: true,
  coveragePathIgnorePatterns: ["index.ts"],
  moduleNameMapper: {
    "\\.(css|less|sass|scss)$": "identity-obj-proxy",
    "typeface-open-sans": "<rootDir>/src/test/mocks/fontsMock.ts",
    "typeface-poppins": "<rootDir>/src/test/mocks/fontsMock.ts",
    "^@core/(.*)$": "<rootDir>/src/core/$1",
    "^@icons": "<rootDir>/src/icons",
    "^@icons/(.*)$": "<rootDir>/src/icons/$1",
    "^@system": "<rootDir>/src/system",
    "^@system/(.*)$": "<rootDir>/src/system/$1",
    "^@test-utils/(.*)$": "<rootDir>/src/test/utils/$1",
    "^@theme": "<rootDir>/src/theme",
    "^@theme/(.*)$": "<rootDir>/src/theme/$1",
    "^@utils": "<rootDir>/src/utils",
    "^@utils/(.*)$": "<rootDir>/src/utils/$1",
    "^@vectors": "<rootDir>/src/vectors",
    "^@vectors/(.*)$": "<rootDir>/src/vectors/$1",
    "d3": "<rootDir>/node_modules/d3/dist/d3.min.js",
    "styled-components": "styled-components/dist/styled-components.browser.cjs.js",
  },
};
